{
 "title": "Auto Configured",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ZOS - Insufficient Slots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "galasa_zos_insufficent_slots_total"
    }
   ]
  },
  {
   "title": "Successful Polls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "galasa_metric_successfull_polls"
    }
   ]
  },
  {
   "title": "Runs Made to Wait",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "galasa_runs_made_to_wait_total" }
   ]
  },
  {
   "title": "Number of Submitted Runs",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Number of Submitted Runs" }
   ],
   "targets": [
    {
     "expr": "galasa_k8s_controller_submitted_runs"
    }
   ]
  }
 ]
}