{
 "title": "Auto Generated Board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Automated Runs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per minute" }
   ],
   "targets": [
    {
     "expr": "rate(galasa_runs_automated_started_total[1m])*60"
    }
   ]
  },
  {
   "title": "Local Runs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "per minute" }
   ],
   "targets": [
    {
     "expr": "rate(galasa_runs_local_started_total[1m])*60"
    }
   ]
  },
  {
   "title": "Run Waits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "per minute" }
   ],
   "targets": [
    {
     "expr": "rate(galasa_runs_made_to_wait_total[1m])*60"
    }
   ]
  },
  {
   "title": "Insufficient zOS slots",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "per minute" }
   ],
   "targets": [
    {
     "expr": "rate(galasa_zos_insufficent_slots_total[1m])*60"
    }
   ]
  }
 ]
}